name: ibroadcast-media-sync-lite
version: 0.4.2
summary: MediaSync Lite is a very lean, powerful and simple uploader. 
description: |
    MediaSync Lite is a very lean, powerful and simple uploader for Windows, Mac and also Linux 
    (however the Linux version lacks some of the features of Windows and Mac version). 
    It is configurable to upload 1 - 6 files at the same time and skips files already 
    in your library so you can run it over and over without duplicates. 
    It also creates a debugging log which you can examine to troubleshoot any problems. 
#license: ?

base: core20
confinement: strict
grade: stable

parts:
  ibroadcast-media-sync-lite:
    plugin: make
    stage: [usr/bin/mediasynclite, usr/share]
    prime: [usr/bin/mediasynclite, usr/share]
    source: https://github.com/iBroadcastMediaServices/MediaSyncLiteLinux/archive/master.tar.gz # the repo doesn't have tags/releases
    build-packages: [gcc, make, libgtk-3-dev, libcurl4-openssl-dev, openssl, libssl-dev, libjansson-dev]
    stage-packages: [libgtk-3-dev, libcurl4-openssl-dev, openssl, libssl-dev, libjansson-dev, libasn1-8-heimdal, libcurl4, libgssapi3-heimdal, libhcrypto4-heimdal, libheimbase1-heimdal, libheimntlm0-heimdal, libhx509-5-heimdal, libjansson4, libkrb5-26-heimdal, libldap-2.4-2, libnghttp2-14, libroken18-heimdal, librtmp1, libsasl2-2, libssh-4, libwind0-heimdal]

apps:
  ibroadcast-media-sync-lite:
    extensions: [gnome-3-38]
    command: usr/bin/mediasynclite
    plugs: [network, home, removable-media]

layout:
  /usr/local/share/mediasynclite:
    symlink: $SNAP/share/ui
